const countries = {
  AF: { name: 'Afghanistan', key: 'AF', dial_code: '+93' },
  AL: { name: 'Albania', key: 'AL', dial_code: '+355' },
  DZ: { name: 'Algeria', key: 'DZ', dial_code: '+213' },
  AS: { name: 'American Samoa', key: 'AS', dial_code: '+1684' },
  AD: { name: 'Andorra', key: 'AD', dial_code: '+376' },
  AO: { name: 'Angola', key: 'AO', dial_code: '+244' },
  AI: { name: 'Anguilla', key: 'AI', dial_code: '+1264' },
  AQ: { name: 'Antarctica', key: 'AQ', dial_code: '+672 ' },
  AG: { name: 'Antigua and Barbuda', key: 'AG', dial_code: '+1268' },
  AR: { name: 'Argentina', key: 'AR', dial_code: '+54' },
  AM: { name: 'Armenia', key: 'AM', dial_code: '+374' },
  AW: { name: 'Aruba', key: 'AW', dial_code: '+297' },
  AU: { name: 'Australia', key: 'AU', dial_code: '+61 ' },
  AT: { name: 'Austria', key: 'AT', dial_code: '+43' },
  AZ: { name: 'Azerbaijan', key: 'AZ', dial_code: '+994' },
  BS: { name: 'Bahamas', key: 'BS', dial_code: '+1242' },
  BH: { name: 'Bahrain', key: 'BH', dial_code: '+973' },
  BD: { name: 'Bangladesh', key: 'BD', dial_code: '+880' },
  BB: { name: 'Barbados', key: 'BB', dial_code: '+1246' },
  BY: { name: 'Belarus', key: 'BY', dial_code: '+375' },
  BE: { name: 'Belgium', key: 'BE', dial_code: '+32' },
  BZ: { name: 'Belize', key: 'BZ', dial_code: '+501' },
  BJ: { name: 'Benin', key: 'BJ', dial_code: '+229' },
  BM: { name: 'Bermuda', key: 'BM', dial_code: '+1441' },
  BT: { name: 'Bhutan', key: 'BT', dial_code: '+975' },
  BO: { name: 'Bolivia, Plurinational State of', key: 'BO', dial_code: '+591' },
  BA: { name: 'Bosnia and Herzegovina', key: 'BA', dial_code: '+387' },
  BW: { name: 'Botswana', key: 'BW', dial_code: '+267' },
  BV: { name: 'Bouvet Island', key: 'BV', dial_code: '+47' },
  BR: { name: 'Brazil', key: 'BR', dial_code: '+55' },
  IO: { name: 'British Indian Ocean Territory', key: 'IO', dial_code: '+246' },
  BN: { name: 'Brunei Darussalam', key: 'BN', dial_code: '+673' },
  BG: { name: 'Bulgaria', key: 'BG', dial_code: '+359' },
  BF: { name: 'Burkina Faso', key: 'BF', dial_code: '+226' },
  BI: { name: 'Burundi', key: 'BI', dial_code: '+257' },
  KH: { name: 'Cambodia', key: 'KH', dial_code: '+855' },
  CM: { name: 'Cameroon', key: 'CM', dial_code: '+237' },
  CA: { name: 'Canada', key: 'CA', dial_code: '+1' },
  CV: { name: 'Cape Verde', key: 'CV', dial_code: '+238' },
  BQ: { name: 'Caribbean Netherlands', key: 'BQ', dial_code: '+599' },
  KY: { name: 'Cayman Islands', key: 'KY', dial_code: '+345' },
  CF: { name: 'Central African Republic', key: 'CF', dial_code: '+236' },
  TD: { name: 'Chad', key: 'TD', dial_code: '+235' },
  CL: { name: 'Chile', key: 'CL', dial_code: '+56' },
  CN: {
    name: "China (People's Republic of China)",
    key: 'CN',
    dial_code: '+86'
  },
  CX: { name: 'Christmas Island', key: 'CX', dial_code: ' +61' },
  CC: { name: 'Cocos (Keeling) Islands', key: 'CC', dial_code: '+61' },
  CO: { name: 'Colombia', key: 'CO', dial_code: '+57' },
  KM: { name: 'Comoros', key: 'KM', dial_code: '+269' },
  CD: {
    name: 'Congo, the Democratic Republic of the',
    key: 'CD',
    dial_code: '+243'
  },
  CK: { name: 'Cook Islands', key: 'CK', dial_code: '+682' },
  CR: { name: 'Costa Rica', key: 'CR', dial_code: '+506' },
  HR: { name: 'Croatia', key: 'HR', dial_code: '+385' },
  CU: { name: 'Cuba', key: 'CU', dial_code: '+53' },
  CW: { name: 'CuraÃƒÆ’Ã‚Â§ao', key: 'CW', dial_code: '+599' },
  CY: { name: 'Cyprus', key: 'CY', dial_code: '+357' },
  CZ: { name: 'Czech Republic', key: 'CZ', dial_code: '+420' },
  CI: { name: "CÃƒÆ’Ã‚Â´te d'Ivoire", key: 'CI', dial_code: '+225' },
  DK: { name: 'Denmark', key: 'DK', dial_code: '+45' },
  DJ: { name: 'Djibouti', key: 'DJ', dial_code: '+253' },
  DM: { name: 'Dominica', key: 'DM', dial_code: '+1767' },
  DO: { name: 'Dominican Republic', key: 'DO', dial_code: '+1849' },
  EC: { name: 'Ecuador', key: 'EC', dial_code: '+593' },
  EG: { name: 'Egypt', key: 'EG', dial_code: '+20' },
  SV: { name: 'El Salvador', key: 'SV', dial_code: '+503' },
  'GB-ENG': { name: 'England', key: 'GB-ENG', dial_code: '+44' },
  GQ: { name: 'Equatorial Guinea', key: 'GQ', dial_code: '+240' },
  ER: { name: 'Eritrea', key: 'ER', dial_code: '+291' },
  EE: { name: 'Estonia', key: 'EE', dial_code: '+372' },
  ET: { name: 'Ethiopia', key: 'ET', dial_code: '+251' },
  EU: { name: 'Europe', key: 'EU', dial_code: '+44' },
  FK: { name: 'Falkland Islands (Malvinas)', key: 'FK', dial_code: '+500' },
  FO: { name: 'Faroe Islands', key: 'FO', dial_code: '+298' },
  FJ: { name: 'Fiji', key: 'FJ', dial_code: '+679' },
  FI: { name: 'Finland', key: 'FI', dial_code: '+358' },
  FR: { name: 'France', key: 'FR', dial_code: '+33' },
  GF: { name: 'French Guiana', key: 'GF', dial_code: '+594' },
  PF: { name: 'French Polynesia', key: 'PF', dial_code: '+689' },
  TF: { name: 'French Southern Territories', key: 'TF', dial_code: '+262' },
  GA: { name: 'Gabon', key: 'GA', dial_code: '+241' },
  GM: { name: 'Gambia', key: 'GM', dial_code: '+220' },
  GE: { name: 'Georgia', key: 'GE', dial_code: '+995' },
  DE: { name: 'Germany', key: 'DE', dial_code: '+49' },
  GH: { name: 'Ghana', key: 'GH', dial_code: '+233' },
  GI: { name: 'Gibraltar', key: 'GI', dial_code: '+350' },
  GR: { name: 'Greece', key: 'GR', dial_code: '+30' },
  GL: { name: 'Greenland', key: 'GL', dial_code: '+299' },
  GD: { name: 'Grenada', key: 'GD', dial_code: '+1473' },
  GP: { name: 'Guadeloupe', key: 'GP', dial_code: '+590' },
  GU: { name: 'Guam', key: 'GU', dial_code: '+1671' },
  GT: { name: 'Guatemala', key: 'GT', dial_code: '+502' },
  GG: { name: 'Guernsey', key: 'GG', dial_code: '+44' },
  GN: { name: 'Guinea', key: 'GN', dial_code: '+224' },
  GW: { name: 'Guinea-Bissau', key: 'GW', dial_code: '+245' },
  GY: { name: 'Guyana', key: 'GY', dial_code: '+592' },
  HT: { name: 'Haiti', key: 'HT', dial_code: '+509' },
  HM: {
    name: 'Heard Island and McDonald Islands',
    key: 'HM',
    dial_code: '+672'
  },
  VA: { name: 'Holy See (Vatican City State)', key: 'VA', dial_code: '+379' },
  HN: { name: 'Honduras', key: 'HN', dial_code: '+504' },
  HK: { name: 'Hong Kong', key: 'HK', dial_code: '+852' },
  HU: { name: 'Hungary', key: 'HU', dial_code: '+36' },
  IS: { name: 'Iceland', key: 'IS', dial_code: '+354' },
  IN: { name: 'India', key: 'IN', dial_code: '+91' },
  ID: { name: 'Indonesia', key: 'ID', dial_code: '+62' },
  IR: { name: 'Iran, Islamic Republic of', key: 'IR', dial_code: '+98' },
  IQ: { name: 'Iraq', key: 'IQ', dial_code: '+964' },
  IE: { name: 'Ireland', key: 'IE', dial_code: '+353' },
  IM: { name: 'Isle of Man', key: 'IM', dial_code: '+44 ' },
  IL: { name: 'Israel', key: 'IL', dial_code: '+972' },
  IT: { name: 'Italy', key: 'IT', dial_code: '+39' },
  JM: { name: 'Jamaica', key: 'JM', dial_code: '+1876' },
  JP: { name: 'Japan', key: 'JP', dial_code: '+81' },
  JE: { name: 'Jersey', key: 'JE', dial_code: ' +44' },
  JO: { name: 'Jordan', key: 'JO', dial_code: '+962' },
  KZ: { name: 'Kazakhstan', key: 'KZ', dial_code: '+7 ' },
  KE: { name: 'Kenya', key: 'KE', dial_code: '+254' },
  KI: { name: 'Kiribati', key: 'KI', dial_code: '+686' },
  KP: {
    name: "Korea, Democratic People's Republic of",
    key: 'KP',
    dial_code: '+850'
  },
  KR: { name: 'Korea, Republic of', key: 'KR', dial_code: '+82' },
  XK: { name: 'Kosovo', key: 'XK', dial_code: '+383' },
  KW: { name: 'Kuwait', key: 'KW', dial_code: '+965' },
  KG: { name: 'Kyrgyzstan', key: 'KG', dial_code: '+996' },
  LA: {
    name: "Laos (Lao People's Democratic Republic)",
    key: 'LA',
    dial_code: '+856'
  },
  LV: { name: 'Latvia', key: 'LV', dial_code: '+371' },
  LB: { name: 'Lebanon', key: 'LB', dial_code: '+961' },
  LS: { name: 'Lesotho', key: 'LS', dial_code: '+266' },
  LR: { name: 'Liberia', key: 'LR', dial_code: '+231' },
  LY: { name: 'Libya', key: 'LY', dial_code: '+218' },
  LI: { name: 'Liechtenstein', key: 'LI', dial_code: '+423' },
  LT: { name: 'Lithuania', key: 'LT', dial_code: '+370' },
  LU: { name: 'Luxembourg', key: 'LU', dial_code: '+352' },
  MO: { name: 'Macao', key: 'MO', dial_code: '+853' },
  MG: { name: 'Madagascar', key: 'MG', dial_code: '+261' },
  MW: { name: 'Malawi', key: 'MW', dial_code: '+265' },
  MY: { name: 'Malaysia', key: 'MY', dial_code: '+60' },
  MV: { name: 'Maldives', key: 'MV', dial_code: '+960' },
  ML: { name: 'Mali', key: 'ML', dial_code: '+223' },
  MT: { name: 'Malta', key: 'MT', dial_code: '+356' },
  MH: { name: 'Marshall Islands', key: 'MH', dial_code: '+692' },
  MQ: { name: 'Martinique', key: 'MQ', dial_code: '+596' },
  MR: { name: 'Mauritania', key: 'MR', dial_code: '+222' },
  MU: { name: 'Mauritius', key: 'MU', dial_code: '+230' },
  YT: { name: 'Mayotte', key: 'YT', dial_code: '+262' },
  MX: { name: 'Mexico', key: 'MX', dial_code: '+52' },
  FM: { name: 'Micronesia, Federated States of', key: 'FM', dial_code: '+691' },
  MD: { name: 'Moldova, Republic of', key: 'MD', dial_code: '+373' },
  MC: { name: 'Monaco', key: 'MC', dial_code: '+377' },
  MN: { name: 'Mongolia', key: 'MN', dial_code: '+976' },
  ME: { name: 'Montenegro', key: 'ME', dial_code: '+382' },
  MS: { name: 'Montserrat', key: 'MS', dial_code: '+1664' },
  MA: { name: 'Morocco', key: 'MA', dial_code: '+212' },
  MZ: { name: 'Mozambique', key: 'MZ', dial_code: '+258' },
  MM: { name: 'Myanmar', key: 'MM', dial_code: '+95' },
  NA: { name: 'Namibia', key: 'NA', dial_code: '+264' },
  NR: { name: 'Nauru', key: 'NR', dial_code: '+674' },
  NP: { name: 'Nepal', key: 'NP', dial_code: '+977' },
  NL: { name: 'Netherlands', key: 'NL', dial_code: '+31' },
  NC: { name: 'New Caledonia', key: 'NC', dial_code: '+687' },
  NZ: { name: 'New Zealand', key: 'NZ', dial_code: '+64' },
  NI: { name: 'Nicaragua', key: 'NI', dial_code: '+505' },
  NE: { name: 'Niger', key: 'NE', dial_code: '+227' },
  NG: { name: 'Nigeria', key: 'NG', dial_code: '+234' },
  NU: { name: 'Niue', key: 'NU', dial_code: '+683' },
  NF: { name: 'Norfolk Island', key: 'NF', dial_code: '+672' },
  MK: { name: 'North Macedonia', key: 'MK', dial_code: '+389' },
  'GB-NIR': { name: 'Northern Ireland', key: 'GB-NIR', dial_code: '+44' },
  MP: { name: 'Northern Mariana Islands', key: 'MP', dial_code: '+1670' },
  NO: { name: 'Norway', key: 'NO', dial_code: '+47 ' },
  OM: { name: 'Oman', key: 'OM', dial_code: '+968' },
  PK: { name: 'Pakistan', key: 'PK', dial_code: '+92' },
  PW: { name: 'Palau', key: 'PW', dial_code: '+680' },
  PS: { name: 'Palestine', key: 'PS', dial_code: '+970' },
  PA: { name: 'Panama', key: 'PA', dial_code: '+507' },
  PG: { name: 'Papua New Guinea', key: 'PG', dial_code: '+675' },
  PY: { name: 'Paraguay', key: 'PY', dial_code: '+595' },
  PE: { name: 'Peru', key: 'PE', dial_code: '+51' },
  PH: { name: 'Philippines', key: 'PH', dial_code: '+63' },
  PN: { name: 'Pitcairn', key: 'PN', dial_code: '+64' },
  PL: { name: 'Poland', key: 'PL', dial_code: '+48' },
  PT: { name: 'Portugal', key: 'PT', dial_code: '+351' },
  PR: { name: 'Puerto Rico', key: 'PR', dial_code: '+1939' },
  PRI: { name: 'Puerto Rico ', key: 'PRI', dial_code: '+1787' },
  QA: { name: 'Qatar', key: 'QA', dial_code: '+974' },
  CG: { name: 'Republic of the Congo', key: 'CG', dial_code: '+242' },
  RO: { name: 'Romania', key: 'RO', dial_code: '+40' },
  RU: { name: 'Russian Federation', key: 'RU', dial_code: '+7' },
  RW: { name: 'Rwanda', key: 'RW', dial_code: '+250' },
  RE: { name: 'RÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â©union', key: 'RE', dial_code: '+262 ' },
  BL: {
    name: 'Saint BarthÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â©lemy',
    key: 'BL',
    dial_code: '+590 '
  },
  SH: {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    key: 'SH',
    dial_code: '+290'
  },
  KN: { name: 'Saint Kitts and Nevis', key: 'KN', dial_code: '+1869' },
  LC: { name: 'Saint Lucia', key: 'LC', dial_code: '+1758' },
  MF: { name: 'Saint Martin', key: 'MF', dial_code: ' +590' },
  PM: { name: 'Saint Pierre and Miquelon', key: 'PM', dial_code: '+508' },
  VC: {
    name: 'Saint Vincent and the Grenadines',
    key: 'VC',
    dial_code: '+1784'
  },
  WS: { name: 'Samoa', key: 'WS', dial_code: '+685' },
  SM: { name: 'San Marino', key: 'SM', dial_code: '+378' },
  ST: { name: 'Sao Tome and Principe', key: 'ST', dial_code: '+239' },
  SA: { name: 'Saudi Arabia', key: 'SA', dial_code: '+966' },
  'GB-SCT': { name: 'Scotland', key: 'GB-SCT', dial_code: '+44' },
  SN: { name: 'Senegal', key: 'SN', dial_code: '+221' },
  RS: { name: 'Serbia', key: 'RS', dial_code: '+381' },
  SC: { name: 'Seychelles', key: 'SC', dial_code: '+248' },
  SL: { name: 'Sierra Leone', key: 'SL', dial_code: '+232' },
  SG: { name: 'Singapore', key: 'SG', dial_code: '+65' },
  SX: { name: 'Sint Maarten (Dutch part)', key: 'SX', dial_code: '+721' },
  SK: { name: 'Slovakia', key: 'SK', dial_code: '+421' },
  SI: { name: 'Slovenia', key: 'SI', dial_code: '+386' },
  SB: { name: 'Solomon Islands', key: 'SB', dial_code: '+677' },
  SO: { name: 'Somalia', key: 'SO', dial_code: '+252' },
  ZA: { name: 'South Africa', key: 'ZA', dial_code: '+27' },
  GS: {
    name: 'South Georgia and the South Sandwich Islands',
    key: 'GS',
    dial_code: '+500'
  },
  SS: { name: 'South Sudan', key: 'SS', dial_code: '+211' },
  ES: { name: 'Spain', key: 'ES', dial_code: '+34' },
  LK: { name: 'Sri Lanka', key: 'LK', dial_code: '+94' },
  SD: { name: 'Sudan', key: 'SD', dial_code: '+249' },
  SR: { name: 'Suriname', key: 'SR', dial_code: '+597' },
  SJ: { name: 'Svalbard and Jan Mayen Islands', key: 'SJ', dial_code: ' +47' },
  SZ: { name: 'Swaziland', key: 'SZ', dial_code: '+268' },
  SE: { name: 'Sweden', key: 'SE', dial_code: '+46' },
  CH: { name: 'Switzerland', key: 'CH', dial_code: '+41' },
  SY: { name: 'Syrian Arab Republic', key: 'SY', dial_code: '+963' },
  TW: { name: 'Taiwan (Republic of China)', key: 'TW', dial_code: '+886' },
  TJ: { name: 'Tajikistan', key: 'TJ', dial_code: '+992' },
  TZ: { name: 'Tanzania, United Republic of', key: 'TZ', dial_code: '+255' },
  TH: { name: 'Thailand', key: 'TH', dial_code: '+66' },
  TL: { name: 'Timor-Leste', key: 'TL', dial_code: '+670' },
  TG: { name: 'Togo', key: 'TG', dial_code: '+228' },
  TK: { name: 'Tokelau', key: 'TK', dial_code: '+690' },
  TO: { name: 'Tonga', key: 'TO', dial_code: '+676' },
  TT: { name: 'Trinidad and Tobago', key: 'TT', dial_code: '+1868' },
  TN: { name: 'Tunisia', key: 'TN', dial_code: '+216' },
  TR: { name: 'Turkey', key: 'TR', dial_code: '+90' },
  TM: { name: 'Turkmenistan', key: 'TM', dial_code: '+993' },
  TC: { name: 'Turks and Caicos Islands', key: 'TC', dial_code: '+1649' },
  TV: { name: 'Tuvalu', key: 'TV', dial_code: '+688' },
  UM: { name: 'US Minor Outlying Islands', key: 'UM', dial_code: '+246' },
  UG: { name: 'Uganda', key: 'UG', dial_code: '+256' },
  UA: { name: 'Ukraine', key: 'UA', dial_code: '+380' },
  AE: { name: 'United Arab Emirates', key: 'AE', dial_code: '+971' },
  GB: { name: 'United Kingdom', key: 'GB', dial_code: '+ 44' },
  US: { name: 'United States', key: 'US', dial_code: '+1 ' },
  UY: { name: 'Uruguay', key: 'UY', dial_code: '+598' },
  UZ: { name: 'Uzbekistan', key: 'UZ', dial_code: '+998' },
  VU: { name: 'Vanuatu', key: 'VU', dial_code: '+678' },
  VE: {
    name: 'Venezuela, Bolivarian Republic of',
    key: 'VE',
    dial_code: '+58'
  },
  VN: { name: 'Vietnam', key: 'VN', dial_code: '+84' },
  VG: { name: 'Virgin Islands, British', key: 'VG', dial_code: '+1284' },
  VI: { name: 'Virgin Islands, U.S.', key: 'VI', dial_code: '+1340' },
  'GB-WLS': { name: 'Wales', key: 'GB-WLS', dial_code: '+44' },
  WF: { name: 'Wallis and Futuna Islands', key: 'WF', dial_code: '+681' },
  EH: { name: 'Western Sahara', key: 'EH', dial_code: '+212' },
  YE: { name: 'Yemen', key: 'YE', dial_code: '+967' },
  ZM: { name: 'Zambia', key: 'ZM', dial_code: '+260' },
  ZW: { name: 'Zimbabwe', key: 'ZW', dial_code: '+263' },
  AX: { name: 'ÃƒÆ’Ã¢â‚¬Â¦land Islands', key: 'AX', dial_code: '+358 ' }
}

export default countries
